#
# Lumifyx Tx6 LED Display control driver
#
# Written by: John <john.zhao@lumifyx.com>
#
# Copyright (C) 2022 Lingye Technologies Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
KBUILD_CFLAGS +=-Wno-error=format
obj-$(CONFIG_LUMIFYX_FD655)	+= lumifyx-fd655.o



